<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHBcnXSb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHBcnXSb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHBcnXSb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHBcnXSb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHBcnXSb\App_KernelDevDebugContainer([
    'container.build_hash' => 'HBcnXSb',
    'container.build_id' => '7815dd23',
    'container.build_time' => 1655502405,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHBcnXSb');
